baseURL = "http://www.mikeyobrien.com"
languageCode = "en-us"
title = "Mikey O'Brien"
theme = "addison"
googleAnalytics = "UA-34179203-1"

[menu]
  [[menu.main]]
  identifier = "about"
  name = "Software Engineer | Austin, TX"
  url = "/about/"
  weight = 1

[deployment]
order = [".jpg$", ".gif$"]
  [[deployment.targets]]
  name="s3"
  # S3
  URL = "s3://mikeyobrien.com?region=us-west-2"

  [[deployment.matchers]]
  pattern = "^.+\\.(html|xml|json)$"
  gzip = true
