#+title: All Posts
#+hugo_base_dir: ../

* DONE Blogging with org-mode and ox-hugo :tag1:@category1:
:PROPERTIES:
:EXPORT_FILE_NAME: Blogging with ox-hugo
:END:
Walking through steps I took to setup a blog using org-mode for content creation, on MacOS w/ doom emacs.
To deploy the blog I am using free github pages.
** Setting up Hugo
*** 1. Install go and hugo.
   #+begin_src
brew install hugo
   #+end_src
   Follow instructions at: https://go.dev/doc/install

   As a user of nix, I simply start a dev shell using a flake.
*** 2. Add hugo support to your config.el
   #+begin_src
(org +hugo)
   #+end_src
Sync and reload emacs =doom sync=, within emacs type sequence =SPC q R=
*** 3. Create a new hugo directory, add a theme, install mods
**** a. Create directory and enable mods
      #+begin_src
mkdir blog
cd blog
hugo site new .
hugo mod init github.com/<username>/<repo>
mkdir content-org
      #+end_src
**** b. Add theme to config.toml, I'm using PaperMod (insert link)
      #+begin_src
[module]
  [[module.imports]]
    path = "github.com/adityatelange/hugo-PaperMod"
      #+end_src
**** c. init theme
      #+begin_src
hugo mod get -u
      #+end_src
**** d. start server =hugo server --buildDrafts --navigateToChanged=
*** 4. Start blogging
   Create a new post in =content-org/all-posts.org=, insert the following to demo,
   #+begin_example
,#+hugo_base_dir: ../
,* My first post                                             :tag1:@category1:
:PROPERTIES:
:EXPORT_FILE_NAME: my-first-post
:END:
This is my post body
   #+end_example

   Export the post =C-c C-e H H=
**
** Deploying
To deploy I'm leveraging free Github pages. This method will deploy my blog whenever I push to github. Repo must be at =github.com/<username>/<username>.github.io=
*** 1. Add the github action to =./github/workflows/gh-pages.yml=
#+begin_src
name: github pages

on:
  push:
    branches:
      - main  # Set a branch that will trigger a deployment
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
#+end_src
*** 2. Add custom domain to =static/CNAME= file
*** 3. Update DNS to point to =<username>.github.io=

** Acknowledgements
- For more detailed installation instructions for ox-hugo see official instructions here: https://ox-hugo.scripter.co/doc/quick-start/
